# Generated by Django 5.2.11 on 2026-02-14 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200, verbose_name='Hujjat turi nomi')),
                ('tavsif', models.TextField(blank=True, verbose_name='Tavsif')),
                ('majburiy', models.BooleanField(default=True, verbose_name='Majburiy')),
                ('tartib', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Hujjat turi',
                'verbose_name_plural': 'Hujjat turlari',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holat', models.CharField(choices=[('yangi', 'Yangi'), ('korib_chiqilmoqda', "Ko'rib chiqilmoqda"), ('qabul_qilindi', 'Qabul qilindi'), ('rad_etildi', 'Rad etildi')], default='yangi', max_length=20, verbose_name='Holat')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('yangilangan_sana', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('abituriyent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arizalar', to=settings.AUTH_USER_MODEL, verbose_name='Abituriyent')),
                ('qabul_davri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arizalar', to='core.admissioncampaign', verbose_name='Qabul davri')),
                ('yonalish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arizalar', to='core.specialty', verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'ordering': ['-yaratilgan_sana'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fayl', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Fayl')),
                ('holat', models.CharField(choices=[('yuklangan', 'Yuklangan'), ('tekshirilmoqda', 'Tekshirilmoqda'), ('tasdiqlangan', 'Tasdiqlangan'), ('rad_etildi', 'Rad etildi')], default='yuklangan', max_length=20, verbose_name='Holat')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh (xodim uchun)')),
                ('yuklangan_sana', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan sana')),
                ('ariza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hujjatlar', to='applications.application', verbose_name='Ariza')),
                ('tekshirgan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tekshirgan_hujjatlar', to=settings.AUTH_USER_MODEL, verbose_name='Tekshirgan xodim')),
                ('hujjat_turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.documenttype', verbose_name='Hujjat turi')),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
                'ordering': ['hujjat_turi__tartib'],
            },
        ),
    ]
