# Generated by Django 5.2.11 on 2026-02-14 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200, verbose_name='Qabul davri nomi')),
                ('yil', models.PositiveIntegerField(verbose_name='Yil')),
                ('boshlanish_sanasi', models.DateField(verbose_name='Boshlanish sanasi')),
                ('tugash_sanasi', models.DateField(verbose_name='Tugash sanasi')),
                ('faol', models.BooleanField(default=False, verbose_name='Faol')),
                ('tavsif', models.TextField(blank=True, verbose_name='Tavsif')),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Qabul davri',
                'verbose_name_plural': 'Qabul davrlari',
                'ordering': ['-yil'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200, verbose_name='Fakultet nomi')),
                ('kodi', models.CharField(max_length=20, unique=True, verbose_name='Fakultet kodi')),
                ('tavsif', models.TextField(blank=True, verbose_name='Tavsif')),
                ('faol', models.BooleanField(default=True, verbose_name='Faol')),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fakultet',
                'verbose_name_plural': 'Fakultetlar',
                'ordering': ['nomi'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200, verbose_name="Yo'nalish nomi")),
                ('kodi', models.CharField(max_length=20, unique=True, verbose_name="Yo'nalish kodi")),
                ('talim_turi', models.CharField(choices=[('bakalavr', 'Bakalavr'), ('magistr', 'Magistratura')], default='bakalavr', max_length=20, verbose_name="Ta'lim turi")),
                ('kvota', models.PositiveIntegerField(default=0, verbose_name="Kvota (o'rinlar soni)")),
                ('tavsif', models.TextField(blank=True, verbose_name='Tavsif')),
                ('faol', models.BooleanField(default=True, verbose_name='Faol')),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yonalishlar', to='core.faculty', verbose_name='Fakultet')),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalishlar",
                'ordering': ['fakultet', 'nomi'],
            },
        ),
    ]
