# Generated by Django 4.2.28 on 2026-02-15 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=300, verbose_name='OTM nomi')),
                ('kodi', models.CharField(max_length=30, unique=True, verbose_name='OTM kodi')),
                ('turi', models.CharField(choices=[('davlat', 'Davlat OTM'), ('xususiy', 'Nodavlat (Xususiy) OTM'), ('xorijiy', 'Xorijiy OTM filiali'), ('harbiy', 'Harbiy OTM')], default='davlat', max_length=20, verbose_name='OTM turi')),
                ('viloyat', models.CharField(blank=True, max_length=100, verbose_name='Viloyat / Shahar')),
                ('manzil', models.CharField(blank=True, max_length=300, verbose_name='Manzil')),
                ('veb_sayt', models.URLField(blank=True, verbose_name='Veb-sayt')),
                ('tavsif', models.TextField(blank=True, verbose_name='Tavsif')),
                ('faol', models.BooleanField(default=True, verbose_name='Faol')),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OTM (Universitet)',
                'verbose_name_plural': 'OTMlar (Universitetlar)',
                'ordering': ['turi', 'nomi'],
            },
        ),
        migrations.AddField(
            model_name='faculty',
            name='universitet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fakultetlar', to='core.university', verbose_name='OTM'),
        ),
    ]
