# Generated by Django 5.2.11 on 2026-02-14 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otasining_ismi', models.CharField(blank=True, max_length=100, verbose_name='Otasining ismi')),
                ('tugilgan_sana', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon raqami')),
                ('manzil', models.TextField(blank=True, verbose_name='Yashash manzili')),
                ('passport_seriya', models.CharField(blank=True, max_length=20, verbose_name='Passport seriya va raqami')),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='applicant_photos/', verbose_name='Rasm')),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abituriyent profili',
                'verbose_name_plural': 'Abituriyent profillari',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lavozim', models.CharField(blank=True, max_length=100, verbose_name='Lavozimi')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('reviewer', 'Tekshiruvchi')], default='reviewer', max_length=20, verbose_name='Roli')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon raqami')),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xodim profili',
                'verbose_name_plural': 'Xodim profillari',
            },
        ),
    ]
